// Frendz Bingo dares, one per ball in order (index 0 = B1 ... index 74 = O75).
// Sourced from BINGO_INSTRUCTION.docx. Edit here to change dares.

export const DARES: string[] = [
  "Take a selfie with someone from another table and make them do the peace sign",
  "Switch seats with the person to your right - no explanation, just go",
  "Do your most committed chicken dance. Half-effort doesn't count",
  "Stand up and announce your name like you just won an award: \"I'm HELENNNNN!!!\"",
  "Find someone whose name starts with A and high-five them like you're old friends reuniting",
  "Post an IG story RIGHT NOW and tag the person to your right",
  "Find someone whose name starts with J and give them an aggressively enthusiastic high five",
  "Post an IG story RIGHT NOW and tag the person to your left",
  "Say hello to the person on your left in your native tongue - bonus points for a dramatic accent",
  "Shake the hand of the person to your right and hit them with a genuine compliment",
  "Swap Frendz bingo cards with the person on your right. Trust the process",
  "Find someone whose name starts with B and high-five them mid-air",
  "Play rock-paper-scissors with a stranger. Loser owes the winner a compliment",
  "Do 5 push-ups. Yes, here. Yes, now",
  "Ask the person to your left to give you a nickname and use it for the rest of the night",
  "Introduce someone you just met to someone you actually know",
  "Lock eyes with the person on your right and make the goofiest face you've got",
  "Teach your whole table how to say \"Cheers!\" in a language none of them know",
  "Find someone whose name starts with E and high-five them like you planned it",
  "Find someone wearing white, introduce yourself, and ask their go-to karaoke song",
  "Give the person in front of you a compliment so good they have to pause",
  "Speak in a goofy voice until you get your next Bingo mark. Commit to the bit",
  "Look the person in front of you dead in the eye and say \"you have a very nice smile\"",
  "Wave at another table until at least two people wave back",
  "Point at the person on your left and say \"ok Boomer\" with full confidence",
  "Find someone wearing a hat and compliment it like it's couture",
  "Find someone with a tattoo and ask for the story behind it",
  "Give the person to your left a compliment they didn't see coming",
  "Switch seats with the person to your left. Keep it moving",
  "Give everyone at your table a high five in one smooth victory lap",
  "March to the bar and claim your free shot like a champion",
  "Find someone wearing black, introduce yourself, and find one thing in common",
  "Find someone wearing red and introduce yourself with a fake fancy title",
  "Do 3 push-ups. Make eye contact with someone while you do",
  "Invent a secret handshake with the person to your left. Make it complicated",
  "Take a selfie with the person in front of you - both of you mid-laugh",
  "Point at the person in front of you and say \"ok Boomer\" (they started it)",
  "Ask the person to your right to give you a nickname. No vetoes allowed",
  "Tell a fun fact about yourself that nobody at the table would guess",
  "Lock eyes with the person on your left and make your second-goofiest face",
  "Challenge someone to an air hula-hoop showdown. Judges (everyone) decide the winner",
  "Switch seats with the person to your right. The shuffle continues",
  "Do 5 push-ups and dedicate them to someone at your table",
  "Shake the hand of the person to your left and compliment something specific",
  "Invent a secret handshake with someone at the table and practice it twice",
  "Give the person to your right a compliment about their energy tonight",
  "Post an IG story RIGHT NOW and tag the person in front of you",
  "Make your silliest face and take a selfie with the person in front of you",
  "Make your silliest face and take a selfie with the person on your left",
  "Tell a dad joke. The groan is how you know it worked",
  "Find someone whose name starts with D and high-five them with both hands",
  "Swap Frendz bingo cards with the person in front of you. Plot twist",
  "Start a thumb war with the person to your right. Winner gets bragging rights",
  "Find someone whose name starts with M and high-five them like a celebration",
  "Take a selfie with the person to your left doing matching poses",
  "Invent a secret handshake with the person to your right. Add a finishing move",
  "Take a selfie with the person to your right and rate the photo out loud",
  "Say hello to the person on your right in your native tongue, then teach it to them",
  "Hug a stranger! Ask first, then commit fully",
  "Ask the person in front of you to give you a nickname. Wear it with pride",
  "Round up everyone at the bar for a group photo. You're the director",
  "Make your silliest face and take a selfie with the person on your right",
  "Swap Frendz bingo cards with the person on your left. New card, new luck",
  "Invent a secret handshake with the person in front of you and name it",
  "Say hello to the person in front of you in your native tongue with maximum drama",
  "Find someone whose name starts with C and high-five them like you scored a goal",
  "Grab 2 free shots at the bar and recruit a brand-new friend to take one with you",
  "Challenge the person in front of you to a 10-second dance-off. Table judges",
  "Tell a fun fact about literally anything. Confidence sells it",
  "Find someone wearing blue, introduce yourself, and ask where they're from",
  "Find someone whose name starts with N and high-five them like it's a reunion",
  "Visit the next table and high-five every single person there",
  "Talk someone at your table into a goofy selfie, then post it to IG",
  "Challenge someone to a dance-off. Loser buys the next round of vibes",
  "Perform a goofy dance solo. Own the moment, own the floor",
];
