// Frendz Bingo dares, one per ball in order (index 0 = B1 ... index 74 = O75).
//
// GENERATED from the owner's "party-dares" markdown (2026-09-17) by tools/bank/generate-dares.mjs.
// The markdown numbers its dares B1-B15, I16-I30, N31-N45, G46-G60, O61-O75 -- which is exactly
// BINGO_BALLS order, so the array index IS the ball. The generator refuses to emit unless all 75
// are present, contiguously numbered, and in the right column, because dareForBall() looks the
// dare up POSITIONALLY: one missing line would silently shift every dare after it onto the
// wrong ball, and nothing in the app would report an error.
//
// To change the dares, edit the markdown and re-run the generator -- not this file.

export const DARES: string[] = [
  "Take a selfie with a person from another table.",
  "Do 5 squats",
  "Do your best macarena dance!",
  "Start a group dance off!",
  "Find someone with whose name starts with the letter K and give them a hug!",
  "Try to make other people guess your age",
  "Swap any article of clothing or accessory with someone from your table for 10 minutes",
  "Do a conga line around the area!",
  "Give the person to your left a sip of your drink",
  "Introduce yourself and where you're from in a sing-song voice!",
  "Take a funny group picture with everyone on your table",
  "Find someone whose name starts with the letter M and whisper to their ear \"I'M BATMAN\"",
  "VM a friend the song \"happy birthday\" even if it's not their birthday",
  "Sing a song chosen by your friends on the table and do it dramatically",
  "Try to reach your nose with your tongue",
  "Do 5 push-ups or reveal a funny story about you",
  "Pretend to be a clock and act out the current time",
  "Perform to your table a song in a different language",
  "Do your best impression of a baby being born",
  "Spell your name with your butt!",
  "Spell your name with your butt!",
  "Sing \"Jingle Bells\" in a sad tone",
  "Do a staring contest with the person in front of you!",
  "Acting time! Try to do an evil laugh",
  "Let the person to your right tickle you for 10 seconds",
  "Let someone do a .5 forehead picture of you!",
  "Take a serious face selfie with a stranger, post it in your IG stories with the caption \"we did it\"",
  "Show us the funniest photo you have in your camera roll!",
  "Hold hands with everyone in your table and motivate them to get a BINGO!",
  "Without using words, show us what your love language is!",
  "Raise your cards & get a free shot!",
  "Find a person wearing black and introduce yourself dramatically",
  "Walk like a crab across the room",
  "Give a stranger a high five!",
  "Let the person to your right write their name on the palm of your hand",
  "Make any of the hosts laugh!",
  "Make a secret handshake with a stranger",
  "Spin around 5 times and try to walk a straight line",
  "Teach everyone on your table your favorite tongue twister",
  "Give a stranger a compliment!",
  "Let the person to your left give you a dare",
  "Tell everyone on your table a dad joke!",
  "Find someone with the name that starts with N and give them a hug!",
  "Fist bump everyone on the table to your right",
  "Stand Up and say Hi to the table on your left with your new friend",
  "Serenade someone with a dramatic love song",
  "Do your best catwalk!",
  "Acting time! Do your best fake cry",
  "Act like you're stuck in slow motion for 30 seconds.",
  "Try to sing a song chosen by everyone on the table using only the letter Z.",
  "Go to a stranger and tell them who you think is the best dressed person in the rooftop",
  "Find a person wearing a ring & do a shot with them!",
  "Let the person to your left ask you a \"Would you rather...?\" question",
  "Find someone with whose name starts with the letter J & take a selfie with them",
  "Let everyone on the table give you a nickname, you must respond to this nickname only!",
  "Let the person to your right tell a joke but you must keep a straight face!",
  "Find a person wearing white and introduce your friend to them!",
  "Say Hello to the other table in your native tongue!",
  "Look for someone that lives close to where you're from and give them a high five",
  "Dance off! Go to the middle and have a dance off with everyone",
  "Pick a random person on your contacts and text them \"I know what you did\" and don't respond!",
  "Give the person in front of you a dare",
  "Teach everyone on your table to say \"Thank you!\" in a different language",
  "Try to act out a movie scene — with no words.",
  "Celebrity or not! Show everyone on your table a picture of your crush.",
  "Find someone who's not wearing flip flops and ask them to teach you how to say \"I love you\" in a different language",
  "Tell the person to your right your best pick up line!",
  "DM a friend \"Merry Christmas\" together with a group picture of you and your friends",
  "Whenever you hear the hosts say the word \"NEXT\", stand up and yell \"NO!\" for the whole game",
  "Talk like a robot for 30 seconds",
  "Find a person with the name that starts with letter L and give them a compliment",
  "Go to the front and form a heart with your arms/hands",
  "Find someone with piercings and draw a heart on the back of their hands with your non-dominant hand",
  "Sing the Tequila song CORRECTLY!",
  "Act out a charade and let everyone on your table guess",
];
