import { QR } from "../net/pairing";
import { BINGO_ROOM, bingoPosterUrl } from "../net/room";
import { BingoLogo } from "../display/Logo";

// A print-ready join poster for Frendz Bingo. The QR is generated by the app's own QR library and
// encodes the PERMANENT room (bingoPosterUrl), and it uses window.location.origin at runtime — so
// whatever domain you open this page on is the domain baked into the code. Open <origin>/#/poster,
// then print (or screenshot) this page.
export function PosterRoute() {
  return (
    <div className="grid min-h-screen place-items-center bg-white p-8 text-ink">
      <div className="flex flex-col items-center gap-6 text-center">
        <BingoLogo className="text-5xl" />
        <div className="ff-title text-4xl text-grape">SCAN TO JOIN</div>
        <QR text={bingoPosterUrl()} size={460} />
        <div className="font-display text-3xl tracking-[0.3em] text-ink">ROOM {BINGO_ROOM}</div>
        <p className="max-w-md text-lg font-bold text-ink/70">
          Point your phone camera at the code. Follow every ball and dare on your own screen —
          nothing to install.
        </p>
        <p className="text-xs font-semibold text-ink/40 break-all">{bingoPosterUrl()}</p>
      </div>
    </div>
  );
}
