// One mechanism for every game's backdrop art.
//
// The art bible (tools/artbible) tells the generator to save each backdrop at
// `art/<game>/<slug>.webp`, which is served from apps/web/public/art/<game>/<slug>.webp.
// Games are named by their ART id, which is NOT always the source folder name:
// Quick Draw's screens live in src/pictionary, Solo Clue's in src/justone,
// Cover Ops' in src/codenames, Sketch Relay's in src/telestrations.
//
// THE POINT OF THIS FILE: art arrives one game at a time, over weeks. A screen must
// look exactly as it does today until its image actually exists, and must never show
// a broken frame. So useBackdrop() returns an EMPTY style until the image has loaded
// in the browser, and the `.ff-backdrop` gradient underneath is what renders in the
// meantime. Nothing to remove later, and no flag to remember to flip.

import { useEffect, useState } from "react";

export const artUrl = (game: string, slug: string) => `/art/${game}/${slug}.webp`;

/**
 * Style for a `.ff-backdrop` element. Empty object until the image loads, so the
 * element keeps its CSS gradient; once loaded, the inline background overrides it.
 *
 * `dim` darkens the art so the white display text stays readable over it — the
 * backdrop prompts already ask for a dark, uncluttered centre, but the art is
 * generated by a model and the tint is what guarantees contrast rather than hoping.
 */
export function useBackdrop(game: string, slug: string, dim = 0.45): React.CSSProperties {
  const src = artUrl(game, slug);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    setLoaded(false);
    let live = true;
    const img = new Image();
    img.onload = () => { if (live) setLoaded(true); };
    // No onerror handler needed: not loading is the default state, which is the
    // behaviour we want for art that has not been generated yet.
    img.src = src;
    return () => { live = false; };
  }, [src]);

  if (!loaded) return {};
  const tint = `rgba(0,0,0,${dim})`;
  return {
    backgroundImage: `linear-gradient(${tint}, ${tint}), url("${src}")`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    animation: "none",           // the gradient's slow drift would smear a photo
  };
}
